# http://travis-ci.org/#!/aaronhelton/rdflib-sqlalchemy
language: python
branches:
  only:
    - master
env:
    - DB=pgsql
    - DB=mysql
    - DB=sqlite
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then pip install -r requirements-py2.txt --use-mirrors; fi
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then pip install -r requirements-py3.txt --use-mirrors; fi
    - if [[ ${TRAVIS_PYTHON_VERSION} == 'pypy' ]]; then pip install --upgrade 'git+https://github.com/gjhiggins/isodate#egg=isodate'; fi
    - python setup.py install
before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS rdflibsqla_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database rdflibsqla_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS rdflibsqla_test'; fi"
script:
    # Must cd somewhere else so python3 doesn't get confused and run
    # the python2 code from the current directory instead of the installed
    # 2to3 version.
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then nosetests; fi
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then nosetests --where=./build/src; fi
    
